### ISSUE TITLE
Image downloads but not showing

### ISSUE THREAD

**Issue by Dark7Thunder** [Proxtx/caption#5]
It downloads but all I get is a black and white blocky background, it's like one of those pngs without a background.

Edit: I used this on Librewolf first, Just tried it on brave and it works find.

**Comment by Proxtx** [comment]
Thanks for the report. I will look into that. Does it work if you click on preview?

**Comment by Proxtx** [comment]
Hey I figured it out. In librewolf a small image icon should appear on the left of the url. Click it and allow access. Now the image should download properly.
